In [2]:
import numpy as np

In [5]:
input_data = np.array([1,2,3])

In [19]:
input_data.transpose()

array([1, 2, 3])

In [12]:
np.vstack((input_data.T, np.ones((1,3))))


array([[1., 2., 3.],
       [1., 1., 1.]])

In [15]:
np.ones(shape=(1,3))

array([[1., 1., 1.]])